[package]
name = "yuhaiin-dns"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
async-proxy = ["dep:futures-util", "dep:hickory-resolver", "dep:tokio"]
http2 = ["async-proxy", "dep:bytes", "dep:h2", "dep:http"]
tls = [
    "http2",
    "async-proxy",
    "dep:rustls",
    "dep:rustls-rustcrypto",
    "dep:tokio-rustls",
    "dep:p256-tls-auto",
    "dep:sha2_10",
    "dep:ed25519-tls-auto",
    "dep:rsa-tls-auto",
    "dep:signature-tls-auto",
    "dep:webpki-roots",
]
quic = ["async-proxy", "dep:quinn", "dep:rustls", "dep:webpki-roots"]

[dependencies]
bytes = { version = "1.12.1", optional = true }
futures-util = { version = "0.3.33", optional = true, default-features = false, features = ["std"] }
hickory-proto = { version = "0.26.1", default-features = false, features = ["std"] }
h2 = { version = "0.4.15", optional = true }
http = { version = "1.5.0", optional = true }
ed25519-tls-auto = { package = "ed25519-dalek", version = "2.2.0", optional = true, default-features = false, features = ["std", "pkcs8"] }
p256-tls-auto = { package = "p256", version = "0.13.2", optional = true, default-features = false, features = ["ecdsa", "pem", "pkcs8", "std"] }
quinn = { version = "0.11.11", optional = true, default-features = false, features = ["runtime-tokio", "rustls-ring"] }
rustls = { version = "0.23.41", optional = true, default-features = false, features = ["std", "tls12"] }
rsa-tls-auto = { package = "rsa", version = "0.9.10", optional = true, default-features = false, features = ["std", "pem", "sha2"] }
rustls-rustcrypto = { version = "0.0.2-alpha", optional = true, default-features = false, features = ["std", "tls12", "zeroize"] }
sha2_10 = { package = "sha2", version = "0.10.9", optional = true, features = ["oid"] }
signature-tls-auto = { package = "signature", version = "2.2.0", optional = true, default-features = false, features = ["alloc", "rand_core"] }
tokio-rustls = { version = "0.26.4", optional = true, default-features = false, features = ["tls12"] }
webpki-roots = { version = "1.0.3", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.50.0", optional = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync", "time"] }
yuhaiin-types = { path = "../yuhaiin-types" }

[lints]
workspace = true

[dev-dependencies]
quinn = { version = "0.11.11", default-features = false, features = ["runtime-tokio", "rustls-ring"] }
rustls-pemfile = "2.2.0"

[target.'cfg(target_os = "windows")'.dependencies]
hickory-resolver = { version = "0.26.1", optional = true, default-features = false, features = ["system-config", "tokio"] }
