[package]
name = "yuhaiin-wireguard"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22.1"
boringtun = { version = "0.7.1", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
socket2 = { version = "0.6.5", default-features = false, features = ["all"] }
smoltcp = { version = "0.13.1", default-features = false, features = ["std", "medium-ip", "proto-ipv4", "proto-ipv6", "socket-tcp", "socket-udp", "async"] }
tokio = { version = "1.50.0", default-features = false, features = ["io-util", "macros", "net", "rt", "sync", "time"] }
yuhaiin-core = { path = "../yuhaiin-core", features = ["async-proxy", "tun"] }

[lints]
workspace = true

[dev-dependencies]
futures-lite = "2.6.1"
hex = "0.4.3"
